blog/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    # path('', admin.site.urls),
    path('',views.IndexView.as_view(),name='index'),
    path('signup/',views.SignupFormView.as_view(),name='signup'),
    path('login/',views.LoginFormView.as_view(),name='login'),
    path('logout', views.auth_logout, name='auth_logout'),
    path('search/',views.SearchView.as_view(),name='search'),
    path('post/<int:post_id>/',views.PostView.as_view(),name='post-detail'),###文章详情页
    path('add_post/<int:addpost_id>/',views.AddPostModelFormView.as_view(),name='post-add'),###文章详情页
    

    path('tag/<int:tag_id>/',views.TagView.as_view(),name='tag-list'),##展示这个标签下的所有文章 ，还是以card样式展示，所以继承indexview，只是过滤post对象
    path('category/<int:category_id>/',views.CategoryView.as_view(),name='category-list'),##展示这个分类下的所有文章 ，还是以card样式展示
    path('owner/<int:owner_id>/',views.OwnerView.as_view(),name='owner-list'),##展示这个作者下的所有文章 ，还是以card样式展示

]

comment/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'comment'

urlpatterns = [
    path('<int:post_id>/add_comment/',views.CommentFormView.as_view(),name='post-comment'),
    path('<int:post_id>/add_reply/',views.CommentReplyFormView.as_view(),name='post-comment-reply'),
    path('notice/',views.NotificationView.as_view(),name='comment-notice'),

]

hdxsite/urls.py
from django.contrib import admin
from django.contrib.admin import AdminSite
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap

from blog.feeds import AllPostRssFeed
from blog.sitemaps import PostSitemap
from django.contrib.auth import views as auth_views

import notifications.urls

sitemaps = {
    'posts':PostSitemap,
}


urlpatterns = [
    # path('',),####    参考链接默认值？？？
    path('', include('blog.urls'),name='blog'),
    path('comment/', include('comment.urls'),name='comment'),
    path('tool/', include('tool.urls'),name='tool'),
    path('accounts/', include('allauth.urls'),name='allauth'),

    path('simditor/', include('simditor.urls'),name='simditor'),
    path('inbox/notifications/', include('notifications.urls'),name='notifications'),

    path('rss/feed/', AllPostRssFeed(),name='RSS'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('admin/',admin.site.urls),

    
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


from simditor.fields import RichTextField
'''
verbose_name=None, name=None, primary_key=False,
        max_length=None, unique=False, blank=False, null=False,
        db_index=False, rel=None, default=NOT_PROVIDED, editable=True,
        serialize=True, unique_for_date=None, unique_for_month=None,
        unique_for_year=None, choices=None, help_text='', db_column=None,
        db_tablespace=None, auto_created=False, validators=(),
        error_messages=None
'''
'''
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True ###just change the str 'TRUE/FALSE' to the slogan
    was_published_recently.short_description = 'Published recently?'
'''
class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="名称")
    owner = models.ForeignKey(User, verbose_name="作者",on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = '分类'

    def __str__(self):
        return self.name

class Tag(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    name = models.CharField(max_length=10, verbose_name="名称")
    owner = models.ForeignKey(User, verbose_name="作者",on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = '标签'

    def __str__(self):
        return self.name


class Post(models.Model):

    STATUS_NORMAL = 0
    STATUS_DELETE = 1
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    status = models.PositiveIntegerField(verbose_name="状态",default=STATUS_NORMAL,choices=STATUS_ITEMS)
    title = models.CharField(max_length=255, verbose_name="标题")
    abstract = models.TextField(max_length=1024, blank=True, verbose_name="摘要")
    content = RichTextField(verbose_name="文章正文")
    category = models.ForeignKey(Category, verbose_name="分类",on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, verbose_name="标签")
    owner = models.ForeignKey(User, verbose_name="作者",blank=True,on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    total_views = models.PositiveIntegerField(default=0,verbose_name="总访问量")

    def __str__(self):
        return self.title

    def update_total_views(self):
        self.total_views += 1
        self.save(update_fields=['total_views'])

    class Meta:
        verbose_name = verbose_name_plural = "文章"
        ordering = ['-id']

blog/forms.py
from django.contrib.auth.models import User
# from django.db.models import
from django import forms
from .models import Post
from comment.models import CommentReply



class SignupForm(forms.Form):
    '''
    '''
    username = forms.CharField(min_length=3, max_length=150, label='用户/手机/邮箱', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=False,label='邮箱',widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(min_length=6,max_length=150,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    re_password = forms.CharField(min_length=6,max_length=150,label='确认密码',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    captcha = forms.CharField(min_length=3, max_length=150,label='输入邀请码', widget=forms.TextInput(attrs={'class': 'form-control'}))


class LoginForm(forms.Form):
    '''
    '''
    username = forms.CharField(min_length=3, max_length=150, label='用户/手机/邮箱', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(min_length=3,max_length=150,label='密码',widget=forms.PasswordInput(attrs={'class':'form-control'}))


class AddPostModelForm(forms.ModelForm):
    '''
    '''
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['total_views', 'update_time']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'abstract': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            # 'content':
            # forms.Textarea(attrs={
            #     'class': 'form-control',
            #     'placeholder': '请使用markdown语法编辑文章'
            # }),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'tag': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.shortcuts import render,render_to_response,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import View,TemplateView,ListView,DetailView,UpdateView,CreateView
from django.db.models import F,Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,logout,login
from django.urls import reverse

from .models import Category,Post,Tag
from .forms import SignupForm,LoginForm,AddPostModelForm
from comment.forms import CommentForm,CommentReplyForm

import markdown
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class AddPostModelFormView(View):
    '''
    创建文章模型表单的View视图，处理get和post两种方法,
    get方法这里整合了修改文章的方式
    '''
    def get(self,request,addpost_id):
        if not addpost_id:
            forms = AddPostModelForm()
            return render(request,'blog/add_post.html',context={'post_forms':forms})
        else:
            post = get_object_or_404(Post,id=addpost_id)
            forms = AddPostModelForm(instance=post)
            return render(request,'blog/add_post.html',context={'post_forms':forms,'delete_update':True})

    def post(self,request,addpost_id):
        if not addpost_id:###这是发表文章入口的判断,区别了发表和(更新,删除),怎么区别更新和删除？？？用button的name和value传值
            forms = AddPostModelForm(request.POST)
        else:
            post = get_object_or_404(Post,id=addpost_id)
            forms = AddPostModelForm(request.POST,instance=post)
        if forms.is_valid():
            post = forms.save(commit=False)
            post.owner = request.user
            if request.POST.get('delete_post',''):
                post.status = Post.STATUS_DELETE
            forms.save()
            if request.POST.get('update_post'):
                return HttpResponseRedirect(reverse('blog:post-detail',kwargs={'post_id':addpost_id}))
            else:
                return HttpResponseRedirect(reverse('blog:index'))
        # else:
        #     return render(request,'blog/add_post.html',context={'post_forms':forms})




class SignupFormView(View):
    '''
    注册表单的View视图，处理get和post两种方法
    '''
    def get(self,request):
        forms = SignupForm()
        return render(request,'blog/signup.html',context={'forms':forms})

    def post(self,request):
        forms = SignupForm(request.POST)###明天看下modelform的参数
        if forms.is_valid():
            if forms.cleaned_data['captcha'] != '978822':
                context = {
                'forms':forms,
                'error': '邀请码错误,请联系博主获取邀请码',
                }
                return render(request,'blog/signup.html',context=context)
            if forms.cleaned_data['re_password'] != forms.cleaned_data['password']:
                context = {
                'forms':forms,
                'error': '两次输入密码不正确,请重新输入密码',
                }
                return render(request,'blog/signup.html',context=context)

            User.objects.create_user(
                username=forms.cleaned_data['username'],
                password=forms.cleaned_data['password'],
                email=forms.cleaned_data['email'],
            ).save()
            return HttpResponseRedirect(reverse('blog:index'))



class LoginFormView(View):
    '''
    登录表单的View视图，处理get和post两种方法
    '''
    def get(self,request):
        forms = LoginForm()
        return render(request,'blog/login.html', context={'forms': forms})

    def post(self,request):
        forms = LoginForm(request.POST)  # 明天看下modelform的参数
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            user = authenticate(username=username,password=password)###校验User
            if user and user.is_active:
                login(request,user)###将用户信息保存在session对话中，否则默认为第一访问的状态
                return HttpResponseRedirect(reverse('blog:index'))
            else:
                context = {
                    'forms':forms,
                    'error': '邮箱或者密码错误，请重新输入',
                }
                # locals().update({## locals返回所有的键值
                #     'error':'邮箱或者密码错误，请重新输入'
                # })
                return render(request,'blog/login.html',context=context)

def auth_logout(request):
    logout(request)
    # return render(request,'blog/index.html')###文章显示不出来了
    return HttpResponseRedirect(reverse('blog:index'))


class IndexView(ListView):
    model = Post
    # queryset = Post.objects.filter(status=Post.STATUS_NORMAL)
    context_object_name = 'post_list'
    template_name = 'blog/index.html'
    paginate_by = 5##每页显示数量

    # login_url = 'login/'## 登录验证是跳转地址
    # redirect_field_name = ''###等同于next 将next这个键的值送入login_url中去

    extra_context = {
        'forms':SignupForm(),
        'random_tag_colors':['btn-primary','btn-secondary','btn-success','btn-info','btn-warning','btn-danger','btn-light','btn-dark']
    }

    def get_queryset(self):###只展示正常的文章
        queryset = super().get_queryset()
        return queryset.filter(status=Post.STATUS_NORMAL)

    def get_ordering(self):
        order_by = self.request.GET.get('order_by', '')
        self.ordering =  order_by
        return self.ordering

    def get_context_data(self):
        context = super().get_context_data()
        order_by = self.request.GET.get('order_by','')
        context.update({
            'order_by': order_by,
        })
        return context



class PostView(DetailView):
    model = Post ##查看源代码，只要指定model，对象返回模型
    template_name = 'blog/detail.html'
    # context_object_name = 'post'
    pk_url_kwarg = 'post_id'###这里和url那边参数相对应

    def get_object(self):
        obj = super().get_object()
        if self.request.user != obj.owner:
            obj.update_total_views()
        return obj

    def get_context_data(self,**kwargs):###关键字参数非常重要
        '''
        '''
        pre_posts = Post.objects.filter(status=Post.STATUS_NORMAL).filter(id__lt=int(self.kwargs.get(self.pk_url_kwarg))).order_by('-id')
        next_posts = Post.objects.filter(status=Post.STATUS_NORMAL).filter(id__gt=int(self.kwargs.get(self.pk_url_kwarg))).order_by('id')
        pre_post = pre_posts[0] if pre_posts else None
        next_post = next_posts[0] if next_posts else None
        context = super().get_context_data(**kwargs)
        context.update({
            'comment_forms':CommentForm(),
            'reply_forms':CommentReplyForm(),
            'pre_post':pre_post,
            'next_post':next_post,
        })
        return context


class CategoryView(IndexView):

    def get_queryset(self):
        '''
        筛选对象
        '''
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        if not category_id:
            return queryset
        return queryset.filter(category__id=category_id)

    def get_context_data(self):
        '''
        传参
        '''
        context = super().get_context_data()
        context.update({
            'category_id': self.kwargs.get('category_id','')
        })
        return context


class OwnerView(IndexView):
    '''
    用来查找制定作者的文章,利用继承indexviw少些几行代码
    '''
    def get_queryset(self):
        queryset = super().get_queryset()
        owner_id = self.kwargs.get('owner_id')
        if not owner_id:
            return queryset
        return queryset.filter(owner__id=owner_id)


class TagView(IndexView):
    '''
    '''

    def get_queryset(self):

        queryset = super().get_queryset()
        tag_id = self.kwargs.get('tag_id')
        if not tag_id:
            return queryset
        return queryset.filter(tag__id=tag_id)

# class TagView(IndexView):
#     '''
#     '''
#     def get_queryset(self):
#         # order_by = self.request.GET.get('order_by', '')
#         # if order_by == 'created_view'
#         queryset = super().get_queryset()
#         tag_id = self.kwargs.get('tag_id')
#         if not tag_id:
#             return queryset
#         return queryset.filter(tag__id=tag_id)



class SearchView(IndexView):

    def get_context_data(self):
        '''
        '''
        context = super().get_context_data()
        context.update({
            'search_keyword': self.request.GET.get('search_keyword', '')
        })
        return context

    def get_queryset(self):
        '''
        '''
        queryset = super().get_queryset()
        print(self.ordering)
        if self.ordering:
            queryset = queryset.order_by(self.ordering)

        keyword = self.request.GET.get('search_keyword')
        if not keyword:
            return queryset
        return queryset.filter(Q(title__icontains=keyword) | Q(abstract__icontains=keyword))

blog/templates/blog/detail.html
{% extends 'blog/base.html'%}
{% load static comment_tags %}

{% block container %}


<div class="container my-4">
    <div class="row">
        {% include 'blog/reply_modal.html' %}
        <div class="col-md-2 mt-4 sidebar" id="sidebar">
            <div class="card hvr-glow mb-2  sidebar__inner" style="display: flex">

                <div class="card-body ">
                    <div class="card-title ">
                        <h5 class="text-center mt-2"><strong>快捷导航</strong></h5>
                        <hr>
                        {{ comment_forms.errors}}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-10 col-lg-10">
            <nav>
                <ol class="breadcrumb bg-light">
                    <li class="breadcrumb-item text-monospace">
                        <a class="hvr-wobble-bottom" href="{% url 'blog:index' %}"><i class="fas fa-home"
                                style="color:rgb(185, 66, 66)">首页</i></a>
                    </li>
                    <li class="breadcrumb-item">
                        <a class="hvr-wobble-bottom" href="{% url 'blog:category-list' post.category.id %}"><i
                                class="fas fa-columns" style="color: rgb(104, 32, 187);">{{ post.category }}</i></a>
                    </li>
                    <li class="breadcrumb-item active">{{ post.title }}</li>
                </ol>
            </nav>

            <div class="card hvr-glow mb-2 text-center" style="display: flex">
                <div class="card-body">
                    <h1 class="card-title">{{ post.title }}</h1>
                    <div class="card-text text-center text-muted">
                        <span class="text-monospace">
                            {{post.total_views}} 阅读· {{post.comments.count}} 评论· {{ post.created_time|date:"Y/m/d" }}发布
                            <a href="#comment_area" style="color: cornflowerblue;"
                                class="hvr-grow no-underline">前往评论</a>
                            {% if user == post.owner %}
                            <a href="{% url 'blog:post-add' post.id %}" style="color: #00aaaa"
                                class="hvr-grow no-underline">编辑</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>

            <div class="card hvr-glow mb-2 " style="display: flex">
                <div class="card-body">
                    <div class="card-title">
                        <ul class="">
                            {{ post.content|safe }}
                        </ul>
                    </div>
                    <div>
                        <br>
                        <br>
                        {% if pre_post %}
                        <a class="btn btn-primary float-left hvr-sweep-to-left" data-toggle="tooltip" data-placement="top" title="{{pre_post.title}}"
                            href="{%url 'blog:post-detail' pre_post.id %}"> <<上一章 </a> 
                        {% endif %} {% if next_post %} 
                        <a class="btn btn-primary float-right hvr-sweep-to-right" data-toggle="tooltip" data-placement="top" title="{{next_post.title}}"
                            href="{%url 'blog:post-detail' next_post.id%}">下一章>>
                        </a>
                        {% endif %}

                    </div>
                </div>
            </div>

            <div class="card hvr-glow mb-2" style="display: flex">
                <div class="card-body">
                    <div>

                        {% if user.is_authenticated %}
                        <form action="{% url 'comment:post-comment' post.id%}" class="" method="POST">
                            {% csrf_token %}
                            <br>
                            <h5>我要发言:</h5>
                            <div class="form-group">
                                {{ comment_forms.media }}
                                {{ comment_forms.content }}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary hvr-icon-bob">
                                    <i class="fas fa-plane hvr-icon"></i>
                                    提交评论
                                </button>
                            </div>
                        </form>
                        {% else %}
                        <h5 class="text-monospace text-center">
                            请<a class="btn btn-outline-primary" href="{% url 'blog:login' %}">登录</a>后回复
                        </h5>
                        {% endif %}
                    </div>

                    <div class="card-text">
                        <div>
                            <br>
                            <h5 id="comment_area" class="text-center alert alert-info">共有{{ post.comments.count }}条评论
                            </h5>
                        </div>

                        <div>
                            {% for comment in  post.comments.all %}
                            <li id="comment_{{comment.id}}" class="pt-2">
                                <div class="ml-2">
                                    <h6 class="">
                                        {{ comment.owner }} {{ forloop.counter }} 楼 -
                                        {{ comment.created_time }}
                                        <small>
                                            <a href="javascript:reply({{comment.id}},'');"><i class="fa fa-reply">回复</i></a>
                                        </small>
                                        
                                    </h6>
                                    <div class="text-muted ml-4">
                                        {{ comment.content|safe }}

                                    </div>
                                        <!-- {% if comment.replies.all %}
                                        <a class="btn btn-secondary" data-toggle="collapse" href="#collapseExample_{{comment.id}}" aria-expanded="false" aria-controls="collapseExample"> 更多评论 </a>
                                        {% endif%} -->
                                        <ul class="text-muted" id="collapseExample_{{comment.id}}">
                                            {% for reply in comment.replies.all %}
                                                {% if reply.reply_comment == comment %}
                                                <li id="reply_{{reply.id}}"> 
                                                    {% if reply.reply %}
                                                    <div>
                                                        <!-- {{ reply.id }} >>> {{ reply.reply.id }} -->
                                                        <a href="#">{{ reply.owner }}</a> 回复给 <a href="#">{{ reply.reply.owner }}</a> - {{ reply.created_time }}
                                                        <small>
                                                            <a href="javascript:reply({{reply.reply_comment.id}},{{reply.id}})"><i class="fa fa-reply">回复</i></a>
                                                        </small>
                                                    </div>
                                                    
                                                    {% else %}
                                                    <div>
                                                        <!-- {{ reply.id }} >>> {{ reply.reply_comment.id }} -->
                                                        <a href="#">{{ reply.owner }}</a> 回复给 <a href="#">{{ reply.reply_comment.owner }}</a> - {{ reply.created_time }}
                                                        <small>
                                                            <a href="javascript:reply({{reply.reply_comment.id}},{{reply.id}})"><i class="fa fa-reply">回复</i></a>
                                                        </small>
                                                    </div>
                                                    {% endif %}
                                                        {{ reply.reply_content|safe }}
                                                </li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                </div>
                                <hr>
                            </li>
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

</div>


<style>
    .sidebar {
        will-change: min-height;
    }

    .sidebar__inner {
        transform: translate(0, 0);
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>
{% endblock %}


{% block deal_with_ckeditor_in_detail %}

<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

{% endblock  %}

blog/templates/blog/footer.html
<nav class="navbar navbar-dark bg-dark justify-content-center">
    <div class="" style="text-align: center; color: lightgrey;">
        <h4>Welcome to hdx's blog</h4>
    </div>
</nav>

blog/templates/blog/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

{% include 'blog/notification_modal.html'%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container">
        <a href="{% url 'blog:index' %}" class="navbar-brand hvr-underline-from-center">Home</a>
        <div class="">
            <ui class="navbar-nav nav ">
                <li class="nav-item mr-2"><a href="{% url 'blog:index' %}" class="nav-link">首页</a></li>
                <li class="nav-item mr-2"><a href="#" class="nav-link">关于我</a></li>
                
                <!-- <li class="nav-item mr-2"><a href="{% url 'django.contrib.sitemaps.views.sitemap' %}" class="nav-link">sitemap</a></li> -->
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle hvr-pop " data-toggle="dropdown" >小工具</a>
                    <ul class="dropdown-menu ">
                        <!-- <a href="#" target="_blank" class="dropdown-item hvr-forward " data-toggle="tooltip" data-placement="right" title="未完成"><i class="fas fa-code" style="color: rgb(9, 31, 228);">python在线编辑器</i></a> -->
                        <a href="{% url 'RSS' %}" class="dropdown-item hvr-forward "><i class="fas fa-book" style="color: rgb(228, 115, 9);">RSS订阅</i></a>
                        <a href="#" class="dropdown-item hvr-forward "><i class="fas fa-cloud" style="color: rgb(193, 184, 243);">待定</i></a>
                    </ul>
                </li>
            </ui>
        </div>
        <div >
            <form class="form-inline" action="{% url 'blog:search' %}" method="GET">
                <input type="search" class="form-control mr-3" name="search_keyword" placeholder="搜索文章"
                    value="{{ search_keyword }}">
                <button class="btn btn-primary" type="submit">搜索</button>
            </form>
        </div>
        <div class="">
            <ui class="navbar-nav nav " >
                {% if user.is_authenticated %}
                    <li class="dropdown nav-item mr-2">
                        <!-- <img style="max-height:40px;" src="{{ user.socialaccount_set.all.0.get_avatar_url }}"> -->
                        
                        <a class="nav-link dropdown-toggle hvr-pop" data-toggle="dropdown" href="#">
                            {% if unread_count %}
                            <span class="badge badge-pill badge-danger">
                                {{ unread_count }}
                            </span>
                            {% endif %}
                            {{ user.username }}
                        </a>
                    
                        <ul class="dropdown-menu dropdown-menu-right">
                            {% if user.socialaccount_set.all.0 %}
                            <a href="#" class="dropdown-item hvr-forward" data-toggle="tooltip" data-placement="left" title="跳转到GitHub主页"><i class="fas fa-user" style="color: rgb(140, 100, 19);">个人中心</i></a>
                            {% endif %}
                            <!-- <a href="#" class="dropdown-item hvr-forward" data-toggle="tooltip" data-placement="left" title="跳转到GitHub主页"><i class="fas fa-user" style="color: rgb(140, 100, 19);">个人中心</i></a> -->
                            <a href="#" class="dropdown-item hvr-forward" data-toggle="modal" data-target="#notification_modal">
                                <i class="fa fa-envelope" style="color: rgb(49, 56, 50);">消息通知
                                {% if unread_count %}
                                <span class="badge badge-pill badge-danger">{{ unread_count }}</span>
                                {% endif %}
                                </i>
                                
                            </a>
                            {% if user.is_superuser %}
                            <a href="{% url 'admin:index' %}" target="_blank" class="dropdown-item hvr-forward"><i class="fas fa-sign-out-alt" style="color: rgb(86, 7, 231);">后台管理</i></a>
                            {% endif %}
                            <a href="{% url 'blog:auth_logout' %}" class="dropdown-item hvr-forward"><i class="fas fa-sign-out-alt" style="color: rgb(230, 74, 27);">退出登录</i></a>
                            <!-- <a href="#" class="dropdown-item hvr-forward" ><i class="fas fa-sign-out-alt" style="color: rgb(140, 100, 19);">暂定</i></a> -->
                        </ul>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item"><a href="{% url 'blog:post-add' 0 %}" class="nav-link btn btn-danger hvr-wobble-bottom"><i class="fas fa-pencil-alt "></i>写文章</a></li>
                    {% endif %}
                {% else %}
                    <li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">登录</a></li>
                    <li class="nav-item"><a href="{% url 'blog:signup' %}" class="nav-link">注册</a></li>
                {% endif %}
            </ui>
        </div>

    </div>
</nav>

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load i18n %}
{% load account socialaccount %}

{% block container %}
<div class="container col-lg-5 col-md-4 col-sm-3 col-2 my-3">
  <div class="card">
    <div class="card-body bg-light">
      <h2 class="text-center">
        登录
        <small>没有账号？<a class="btn btn-sm btn-outline-info" href="{% url 'blog:signup' %}">立即注册</a></small>
      </h2>
      <hr>
      <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ forms.as_p }}
        </div>
        <div class="form-group ">
          <a href="#">忘记密码？</a>
          <button class="btn btn-primary float-right" type="submit">登陆</button>
        </div>
        <div class="form-group text-secondary">
          <strong>{{ error }}</strong>
        </div>
      </form>

        <h5 class="text-muted text-center">快速登录</h5>
        <hr>
        <div class="text-center">
            <a href="/accounts/github/login/?process=login"><i class="fab fa-github"
                    style="font-size: 3em; color: rgb(114, 113, 113);"></i></a>
        </div>
    </div>
  </div>

</div>
{% endblock %}